title: Adam Naamani
email: adamnaamani@gmail.com
description: >-
  I've been an entrepreneur, real estate professional, programmer, and martial arts competitor. Nowadays I focus on investing in the natural resource sector, building software with artificial intelligence, and being a family man.
intro: >-
  I've been an entrepreneur, real estate professional, programmer, and martial arts competitor. Nowadays I focus on investing in the natural resource sector, building software with artificial intelligence, and being a family man. Connect with me on <a href="https://x.com/adamknaamani">X</a>, <a href="https://www.linkedin.com/in/adamnaamani">LinkedIn</a>, <a href="https://www.youtube.com/@adamnaamani">YouTube</a>, <a href="https://github.com/adamnaamani">GitHub</a>, or <a href="mailto:adamnaamani@gmail.com">Email</a>.
baseurl: ""
url: "https://adamnaamani.com"
lang: en

google_analytics: G-QMSZ6Y3Y2G

author:
  name: Adam Naamani
  email: adamnaamani@gmail.com
  url: https://adamnaamani.com
  twitter: adamknaamani

twitter:
  username: adamknaamani
  card: summary

social:
  name: Adam Naamani
  links:
    - https://x.com/adamknaamani
    - https://www.linkedin.com/in/adamnaamani
    - https://www.youtube.com/@adamnaamani
    - https://github.com/adamnaamani

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

permalink: /:slug/

date_format: "%b %-d, %Y"

excerpt_separator: "<!--excerpt-end-->"

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/
  - node_modules/
  - README.md
  - scripts/
  - .sass-cache/
  - .jekyll-cache/
  - .jekyll-metadata
