title: Adam Naamani
email: adamnaamani@gmail.com
description: >-
  I've been an <a href="/about/#entrepreneur">entrepreneur</a>, <a href="/about/#real-estate-professional">real estate professional</a>, <a href="/about/#software-developer">software developer</a>, and <a href="/about/#martial-artist">mixed martial artist</a>. I invest in capital markets primarily in the natural resource sector, and provide real estate advisory services in British Columbia.
intro: |-
  I've been an [entrepreneur](/about/#entrepreneur), [real estate professional](/about/#real-estate-professional), [software developer](/about/#software-developer), and [mixed martial artist](/about/#martial-artist). I invest in capital markets primarily in the natural resource sector, and provide real estate advisory services in British Columbia.

  Find me on [X](https://x.com/adamknaamani), [YouTube](https://www.youtube.com/@adamnaamani), [LinkedIn](https://www.linkedin.com/in/adamnaamani), [GitHub](https://github.com/adamnaamani), or [Email](mailto:adamnaamani@gmail.com).
baseurl: ""
url: "https://adamnaamani.com"
lang: en

google_analytics: G-QMSZ6Y3Y2G

author:
  name: Adam Naamani
  email: adamnaamani@gmail.com
  url: https://adamnaamani.com
  twitter: adamknaamani

twitter:
  username: adamknaamani
  card: summary

social:
  name: Adam Naamani
  links:
    - https://x.com/adamknaamani
    - https://www.linkedin.com/in/adamnaamani
    - https://www.youtube.com/@adamnaamani
    - https://github.com/adamnaamani

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

permalink: /:slug/

date_format: "%b %-d, %Y"

excerpt_separator: "<!--excerpt-end-->"

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/
  - node_modules/
  - README.md
  - scripts/
  - .sass-cache/
  - .jekyll-cache/
  - .jekyll-metadata
